apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache
spec:
  replicas: 4
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: gamadorh1993/docker-exercise:1
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service-by-port
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    app: apache

---
apiVersion: v1
kind: Service
metadata:
  name: my-service-by-ip
spec:
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: apache

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: my-service-by-ip
            port:
              number: 8080
